repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.7            # pick a recent stable
    hooks:
      - id: sqlfluff-lint
        args: ["--dialect", "snowflake"]
        additional_dependencies: ["sqlfluff-templater-dbt"]
        files: "(models|snapshots|tests)/.*\\.(sql|yml)$"
      # Optional: auto-fix (can be slow). Uncomment if you want auto-format on commit.
      # - id: sqlfluff-fix
      #   args: ["--dialect", "snowflake"]
      #   additional_dependencies: ["sqlfluff-templater-dbt"]
      #   files: "(models|snapshots|tests)/.*\\.(sql|yml)$"
