name: reto_project
version: 1.0
config-version: 2

profile: reto_db

model-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]
test-paths: ["tests"]

# Optional constants you can reference in macros (e.g., record_src_const())
vars:
  source_system: TPCH

snapshots:
  reto_project:
    +target_schema: raw_vault
    +persist_docs:
      relation: true
      columns: true

models:
  reto_project:
    # Good global defaults
    +on_schema_change: sync_all_columns
    +persist_docs:
      relation: true
      columns: true

    # STAGING → RETO_DB.STAGING
    staging:
      +schema: staging
      +materialized: view

    # RAW VAULT → RETO_DB.RAW_VAULT
    raw_vault:
      +schema: raw_vault
      +materialized: incremental

    # BUSINESS VAULT → RETO_DB.BUSINESS_VAULT
    business_vault:
      +schema: business_vault
      +materialized: view

    # STAR/MARTS → RETO_DB.STAR
    star:
      +schema: star
      +materialized: table
      reporting:
        +materialized: view   # everything in models/star/reporting/ becomes a view

    reporting:
      +schema: reporting
      +materialized: view
