name: reto_project
version: 1.0
config-version: 2

# Debe coincidir con el nombre del perfil/conexión en dbt Cloud
profile: reto_db

# (Opcional) rutas; si no las pones, dbt usa defaults
model-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  reto_project:

    # STAGING → RETO_DB.STAGING
    staging:
      +schema: staging
      +materialized: view

    # RAW VAULT → RETO_DB.RAW_VAULT
    raw_vault:
      +schema: raw_vault
      +materialized: incremental

    # BUSINESS VAULT → RETO_DB.BUSINESS_VAULT
    business_vault:
      +schema: business_vault
      +materialized: view

    # STAR/MARTS → RETO_DB.STAR
    star:
      +schema: star
      +materialized: table
