version: 2

models:
  # ======================
  # DIMENSIONS
  # ======================
  - name: dim_customer
    description: "Customer dimension (current attributes from BV)."
    columns:
      - name: customer_sk
        description: "Surrogate key (HK) for customer."
        tests: [unique, not_null]
      - name: customer_id
        description: "Source business key."
      - name: market_segment
        description: "Customer segment."
      - name: account_balance
        description: "Current account balance."
      - name: nation_name
        description: "Resolved nation name."
      - name: region_name
        description: "Resolved region name."

  - name: dim_part
    description: "Product/Part dimension (current attributes from BV)."
    columns:
      - name: part_sk
        description: "Surrogate key (HK) for part."
        tests: [unique, not_null]
      - name: part_id
        description: "Source business key."
      - name: part_name
        description: "Name of the product."
      - name: brand
        description: "Brand."
      - name: retail_price
        description: "List price."

  - name: dim_supplier
    description: "Supplier dimension (current attributes from BV)."
    columns:
      - name: supplier_sk
        description: "Surrogate key (HK) for supplier."
        tests: [unique, not_null]
      - name: supplier_id
        description: "Source business key."
      - name: supplier_name
        description: "Supplier name."

  - name: dim_nation
    description: "Nation dimension derived from BV."
    columns:
      - name: nation_sk
        description: "Surrogate key (HK) for nation."
        tests: [unique, not_null]
      - name: nation_id
        description: "Business key."
      - name: nation_name
        description: "Nation name."
      - name: region_name
        description: "Associated region."

  - name: dim_region
    description: "Region dimension derived from BV."
    columns:
      - name: region_sk
        description: "Surrogate key (HK) for region."
        tests: [unique, not_null]
      - name: region_id
        description: "Business key."
      - name: region_name
        description: "Region name."

  # ======================
  # FACT
  # ======================
  - name: fact_sales
    description: "Sales fact at order-part-supplier line grain."
    columns:
      - name: sales_sk
        description: "Line-level surrogate key (link HK)."
        tests: [unique, not_null]

      # Foreign keys to dimensions
      - name: customer_hk
        description: "FK to dim_customer.customer_sk."
        tests:
          - relationships:
              to: ref('dim_customer')
              field: customer_sk

      - name: part_hk
        description: "FK to dim_part.part_sk."
        tests:
          - relationships:
              to: ref('dim_part')
              field: part_sk

      - name: supplier_hk
        description: "FK to dim_supplier.supplier_sk."
        tests:
          - relationships:
              to: ref('dim_supplier')
              field: supplier_sk

      # Dates carried on the fact
      - name: order_date
        description: "Order date."

      - name: ship_date
        description: "Ship date."

      - name: receipt_date
        description: "Receipt date."

      # Basic measure presence
      - name: quantity
        tests: [not_null]
      - name: extended_price
        tests: [not_null]
