version: 2

models:
  # ========================
  # HUBS (BK columns use *_id)
  # ========================
  - name: hub_customer
    description: "Hub table storing unique business keys for customers."
    columns:
      - name: customer_hk
        tests: [unique, not_null]
      - name: customer_id
        tests: [not_null]

  - name: hub_orders
    description: "Hub table storing unique business keys for orders."
    columns:
      - name: order_hk
        tests: [unique, not_null]
      - name: order_id
        tests: [not_null]

  - name: hub_part
    description: "Hub table storing unique business keys for parts."
    columns:
      - name: part_hk
        tests: [unique, not_null]
      - name: part_id
        tests: [not_null]

  - name: hub_supplier
    description: "Hub table storing unique business keys for suppliers."
    columns:
      - name: supplier_hk
        tests: [unique, not_null]
      - name: supplier_id
        tests: [not_null]

  - name: hub_nation
    description: "Hub table storing unique business keys for nations."
    columns:
      - name: nation_hk
        tests: [unique, not_null]
      - name: nation_id
        tests: [not_null]

  - name: hub_region
    description: "Hub table storing unique business keys for regions."
    columns:
      - name: region_hk
        tests: [unique, not_null]
      - name: region_id
        tests: [not_null]

  # ========================
  # LINKS
  # ========================
  - name: link_orders_customer
    description: "Link between orders and customers."
    columns:
      - name: link_hk
        tests: [unique, not_null]
      - name: order_hk
        tests: [not_null]
      - name: customer_hk
        tests: [not_null]

  - name: link_part_supplier
    description: "Link between parts and suppliers (PARTSUPP)."
    columns:
      - name: link_hk
        tests: [unique, not_null]
      - name: part_hk
        tests: [not_null]
      - name: supplier_hk
        tests: [not_null]

  - name: link_order_part_supplier
    description: "Link between orders, parts, suppliers at line-level (LINEITEM)."
    columns:
      - name: link_hk
        tests: [unique, not_null]
      - name: order_hk
        tests: [not_null]
      - name: part_hk
        tests: [not_null]
      - name: supplier_hk
        tests: [not_null]
        