version: 2

models:
  - name: hub_customer
    description: "DV2 Hub for Customer (BK=C_CUSTKEY)."
    columns:
      - name: customer_hk
        tests: [not_null, unique]
      - name: customer_bk
        tests: [not_null]

  - name: hub_order
    description: "DV2 Hub for Order (BK=O_ORDERKEY)."
    columns:
      - name: order_hk
        tests: [not_null, unique]
      - name: order_bk
        tests: [not_null]

  - name: hub_part
    description: "DV2 Hub for Part (BK=P_PARTKEY)."
    columns:
      - name: part_hk
        tests: [not_null, unique]
      - name: part_bk
        tests: [not_null]

  - name: hub_supplier
    description: "DV2 Hub for Supplier (BK=S_SUPPKEY)."
    columns:
      - name: supplier_hk
        tests: [not_null, unique]
      - name: supplier_bk
        tests: [not_null]

  - name: link_order_customer
    description: "DV2 Link: Order ↔ Customer"
    columns:
      - name: link_hk
        tests: [not_null, unique]
      - name: order_hk
        tests:
          - not_null
          - relationships:
              to: ref('hub_order')
              field: order_hk
      - name: customer_hk
        tests:
          - not_null
          - relationships:
              to: ref('hub_customer')
              field: customer_hk

  - name: link_order_part_supplier
    description: "DV2 Link: Order ↔ Part ↔ Supplier (line grain)"
    columns:
      - name: link_hk
        tests: [not_null, unique]
      - name: order_hk
        tests:
          - not_null
          - relationships:
              to: ref('hub_order')
              field: order_hk
      - name: part_hk
        tests:
          - not_null
          - relationships:
              to: ref('hub_part')
              field: part_hk
      - name: supplier_hk
        tests:
          - not_null
          - relationships:
              to: ref('hub_supplier')
              field: supplier_hk

  - name: sat_customer_attributes_view
    description: "Convenience view on top of sat_customer_attributes snapshot with start_dt, end_dt, is_current."
    columns:
      - name: CUSTOMER_HK
        description: "Business key hash for customer."
        tests: [not_null]
      - name: START_DT
        description: "Start date of the SCD2 record (maps from dbt_valid_from)."
        tests: [not_null]
      - name: END_DT
        description: "End date of the SCD2 record (maps from dbt_valid_to)."
      - name: IS_CURRENT
        description: "True if this is the current record for the key."
        tests:
          - accepted_values:
              values: [true, false]

  - name: sat_link_ops_lineattr_view
    description: "Convenience view on top of sat_link_ops_lineattr snapshot with start_dt, end_dt, is_current."
    columns:
      - name: LINK_HK
        description: "Business key hash for order-part-supplier line item."
        tests: [not_null]
      - name: START_DT
        description: "Start date of the SCD2 record (maps from dbt_valid_from)."
        tests: [not_null]
      - name: END_DT
        description: "End date of the SCD2 record (maps from dbt_valid_to)."
      - name: IS_CURRENT
        description: "True if this is the current record for the key."
        tests:
          - accepted_values:
              values: [true, false]
              