version: 2

models:
  # Hubs
  - name: hub_customer
    description: "Hub for customers (business key = CUSTOMER_ID)."
    columns:
      - name: CUSTOMER_HK
        description: "Hash key for customer."
        tests: [not_null, unique]
      - name: CUSTOMER_BK
        description: "Business key for customer (CUSTOMER_ID from source)."
        tests: [not_null, unique]

  - name: hub_orders
    description: "Hub for orders (business key = ORDER_ID)."
    columns:
      - name: ORDER_HK
        tests: [not_null, unique]
      - name: ORDER_BK
        tests: [not_null, unique]

  - name: hub_part
    description: "Hub for parts (business key = PART_ID)."
    columns:
      - name: PART_HK
        tests: [not_null, unique]
      - name: PART_BK
        tests: [not_null, unique]

  - name: hub_supplier
    description: "Hub for suppliers (business key = SUPPLIER_ID)."
    columns:
      - name: SUPPLIER_HK
        tests: [not_null, unique]
      - name: SUPPLIER_BK
        tests: [not_null, unique]

  # Links
  - name: link_orders_customer
    description: "Link between orders and customers."
    columns:
      - name: LINK_HK
        tests: [not_null, unique]
      - name: ORDER_HK
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('hub_orders')
                field: order_hk
      - name: CUSTOMER_HK
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('hub_customer')
                field: customer_hk

  - name: link_order_part_supplier
    description: "Line-level link between order, part, and supplier (includes line_number as dependent key)."
    columns:
      - name: LINK_HK
        tests: [not_null, unique]
      - name: ORDER_HK
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('hub_orders')
                field: order_hk
      - name: PART_HK
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('hub_part')
                field: part_hk
      - name: SUPPLIER_HK
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('hub_supplier')
                field: supplier_hk

  # Satellites (views over snapshots)
  - name: sat_customer_attributes_view
    description: "Current-row customer attributes."
    columns:
      - name: CUSTOMER_HK
        tests: [not_null]
      - name: START_DT
        tests: [not_null]

  - name: sat_link_ops_lineattr_view
    description: "Current-row order line operational attributes."
    columns:
      - name: LINK_HK
        tests: [not_null]
      - name: START_DT
        tests: [not_null]
