version: 2

models:
  - name: vw_sales_flat
    description: "Flattened sales dataset (fact_sales joined to conformed dims) for BI."
    columns:
      - name: CUSTOMER_SK
        tests: [not_null]
      - name: PRODUCT_SK
        tests: [not_null]
      - name: SUPPLIER_SK
        tests: [not_null]
      - name: GEOGRAPHY_SK
        tests: [not_null]
      - name: ORDER_HK
        tests: [not_null]
      - name: LINE_SK
        tests:
          - not_null
          - unique
      - name: ORDER_DATE
        tests: [not_null]
      - name: NET_SALES
        tests: [not_null]

  - name: vw_date_dim
    description: "Calendar view derived from order/ship/receipt dates."
    columns:
      - name: DATE_SK
        tests:
          - not_null
          - unique
      - name: DATE_DAY
        tests: [not_null]
      - name: MONTH
        tests:
          - dbt_utils.expression_is_true:
              expression: "MONTH BETWEEN 1 AND 12"
      - name: QUARTER
        tests:
          - dbt_utils.expression_is_true:
              expression: "QUARTER BETWEEN 1 AND 4"
      - name: YEAR
