version: 2

models:
  - name: bv_customer_geography
    description: "Customer to geography (nation/region) enrichment at customer grain."
    columns:
      - name: CUSTOMER_HK
        tests: [not_null, unique]
      - name: CUSTOMER_ID
        tests: [not_null]
      - name: NATION_ID
      - name: NATION_NAME
      - name: REGION_ID
      - name: REGION_NAME

  - name: bv_lineitem_enriched
    description: "Order-line enrichment combining lineitem, orders (dates), customer sat (segment), part (brand/type), and derived measures."
    columns:
      - name: CUSTOMER_HK
        tests: [not_null]
      - name: PART_HK
        tests: [not_null]
      - name: SUPPLIER_HK
        tests: [not_null]
      - name: ORDER_HK
        tests: [not_null]
      - name: LINK_HK
        tests: [not_null, unique]
      - name: ORDER_DATE
        tests: [not_null]
      - name: NET_SALES
        tests: [not_null]
